version: 2

updates:
  - package-ecosystem: bun
    directory: "/"
    schedule:
      interval: monthly
      day: monday
      time: "09:00"
      timezone: "Europe/Paris"
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"